import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
    return (
        <div>
            <Head>
                <title>YoungGeeks.Inc</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <h1 className='text-blue-500 text-4xl'>The testing of the best</h1>
            </main>
        </div>
    )
}

export default Home
