import type { NextPage } from 'next'
import Head from 'next/head'
import Layout from '../components/Layout/Layout'
import Platform from '../components/LpPage/Platform'

const Home: NextPage = () => {
    return (
        <div>
            <Head>
                <title>YoungGeeks.Inc</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <Layout>
                    <Platform />
                </Layout>
            </main>
        </div>
    )
}

export default Home
